package bloodMod;

public class Ids {
	public static int bloodBag;
	public static final int bloodBag_default = 2831;
	public static int bloodBagBat;
	public static final int bloodBagBat_default = 2800;
	public static int bloodBagBlaze;
	public static final int bloodBagBlaze_default = 2801;
	public static int bloodBagCaveSpider;
	public static final int bloodBagCaveSpider_default = 2802;
	public static int bloodBagChicken;
	public static final int bloodBagChicken_default = 2803;
	public static int bloodBagCow;
	public static final int bloodBagCow_default = 2804;
	public static int bloodBagCreeper;
	public static final int bloodBagCreeper_default = 2805;
	public static int bloodBagEnderDragon;
	public static final int bloodBagEnderDragon_default = 2806;
	public static int bloodBagEnderman;
	public static final int bloodBagEnderman_default = 2807;
	public static int bloodBagGhast;
	public static final int bloodBagGhast_default = 2808;
	public static int bloodBagHorse;
	public static final int bloodBagHorse_default = 2809;
	public static int bloodBagIronGolem;
	public static final int bloodBagIronGolem_default = 2810;
	public static int bloodBagMagmaCube;
	public static final int bloodBagMagmaCube_default = 2811;
	public static int bloodBagMooshroom;
	public static final int bloodBagMooshroom_default = 2812;
	public static int bloodBagOcelot;
	public static final int bloodBagOcelot_default = 2813;
	public static int bloodBagPig;
	public static final int bloodBagPig_default = 2814;
	public static int bloodBagSheep;
	public static final int bloodBagSheep_default = 2815;
	public static int bloodBagSilverfish;
	public static final int bloodBagSilverfish_default = 2816;
	public static int bloodBagSkeleton;
	public static final int bloodBagSkeleton_default = 2817;
	public static int bloodBagSlime;
	public static final int bloodBagSlime_default = 2818;
	public static int bloodBagSnowGolem;
	public static final int bloodBagSnowGolem_default = 2819;
	public static int bloodBagSpider;
	public static final int bloodBagSpider_default = 2820;
	public static int bloodBagSquid;
	public static final int bloodBagSquid_default = 2821;
	public static int bloodBagVillager;
	public static final int bloodBagVillager_default = 2822;
	public static int bloodBagWitch;
	public static final int bloodBagWitch_default = 2823;
	public static int bloodBagWither;
	public static final int bloodBagWither_default = 2824;
	public static int bloodBagWitherSkeleton;
	public static final int bloodBagWitherSkeleton_default = 2825;
	public static int bloodBagWolf;
	public static final int bloodBagWolf_default = 2826;
	public static int bloodBagZombie;
	public static final int bloodBagZombie_default = 2827;
	public static int bloodBagZombiePigman;
	public static final int bloodBagZombiePigman_default = 2828;
	public static int bloodBagZombieVillager;
	public static final int bloodBagZombieVillager_default = 2829;
	public static int needle;
	public static final int needle_default = 2830;
	

}
